# Generated by Django 5.2.8 on 2025-11-07 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_categoriaeventos_remove_evento_cor_evento_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.categoriaeventos'),
        ),
    ]
