# Generated by Django 5.2.7 on 2025-12-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_categoriaeventos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='site_url',
            field=models.URLField(blank=True, help_text='Link do site ou rede social', null=True, verbose_name='URL do evento'),
        ),
    ]
