# Generated by Django 5.2.8 on 2025-12-03 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_evento_site_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='eventos_favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Favoritado por'),
        ),
    ]
