# Generated by Django 5.2.7 on 2025-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_remove_evento_data_evento_cor_evento_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(default='2025-12-31'),
        ),
    ]
