# Generated by Django 5.2.8 on 2025-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
