# Generated by Django 5.2.8 on 2025-11-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor_pin', models.CharField(default='blue', help_text="Cor do pino (ex:'red','blue')", max_length=20)),
                ('icone_pin', models.CharField(default='info-sign', help_text='Nome do ícone do Folium', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cor',
        ),
        migrations.AddField(
            model_name='evento',
            name='site_url',
            field=models.URLField(blank=True, help_text='Link do site ou rede social'),
        ),
    ]
