# Generated by Django 5.2.8 on 2025-11-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0003_categoriarecomendacao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('*', '*(pessimo)'), ('**', '**(ruim)'), ('***', '***(mediano)'), ('****', '****(bom)'), ('*****', '*****(otimo)')], max_length=5, null=True),
        ),
    ]
