# Generated by Django 5.2.8 on 2025-11-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recomendacoes", "0007_alter_categoriarecomendacao_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recomendacao",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recomendacoes",
                to="recomendacoes.categoriarecomendacao",
            ),
        ),
    ]
