# Generated by Django 5.2.8 on 2025-12-03 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0007_alter_categoriarecomendacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='recomendacoes_favoritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
