# Generated by Django 5.2.8 on 2025-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='site_url',
            field=models.URLField(blank=True, help_text='Link do site ou rede social', null=True),
        ),
    ]
