# Generated by Django 5.2.8 on 2025-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_site_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaeventos',
            options={'verbose_name': 'Categoria Evento', 'verbose_name_plural': 'Categoria Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_destaque',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Destaque'),
        ),
    ]
