# Generated by Django 5.2.8 on 2025-11-07 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cor_pin', models.CharField(default='blue', help_text="Cor do pino (ex:'red','blue')", max_length=20)),
                ('icone_pin', models.CharField(default='info-sign', help_text='Nome do ícone do Folium', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos_recomendacoes/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('endereco_texto', models.CharField(blank=True, help_text='Ex: Av. Castelo Branco, 1234', max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('site_url', models.URLField(blank=True, help_text='Link do site ou rede social')),
                ('faixa_preco', models.CharField(blank=True, choices=[('$', '$ (Barato)'), ('$$', '$$ (Médio)'), ('$$$', '$$$ (Caro)')], max_length=3, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recomendacoes.categoriarecomendacao')),
            ],
        ),
    ]
