# Generated by Django 5.2.8 on 2025-11-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='site_url',
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='redeSocial_url',
            field=models.URLField(blank=True, help_text='Link das Redes sociais'),
        ),
    ]
