# Generated by Django 5.2.8 on 2025-11-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0002_remove_recomendacao_site_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriarecomendacao',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de fundo para o card', null=True, upload_to='fotos_categorias/'),
        ),
    ]
