# Generated by Django 5.2.8 on 2025-11-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0004_recomendacao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('★', '★(pessimo)'), ('★★', '★★(ruim)'), ('★★★', '★★★(mediano)'), ('★★★★', '★★★★(bom)'), ('★★★★★', '★★★★★(otimo)')], max_length=5, null=True),
        ),
    ]
