# Generated by Django 5.2.8 on 2025-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacoes', '0006_alter_recomendacao_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriarecomendacao',
            options={'verbose_name': 'Categoria Recomendação', 'verbose_name_plural': 'Categoria Recomendações'},
        ),
        migrations.AlterModelOptions(
            name='recomendacao',
            options={'verbose_name': 'Recomendação', 'verbose_name_plural': 'Recomendações'},
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='redeSocial_url',
            field=models.URLField(blank=True, help_text='Link da pagina do ifood ou rede social'),
        ),
    ]
